# Generated by Django 3.1.1 on 2020-10-01 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ghostpost_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='isBoast',
        ),
        migrations.AddField(
            model_name='post',
            name='choices',
            field=models.BooleanField(choices=[(True, 'Boast'), (False, 'Roast')], default=True),
        ),
    ]
