# Generated by Django 3.1.1 on 2020-10-02 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ghostpost_api', '0004_auto_20201002_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='choice_type',
            field=models.CharField(choices=[('boast', 'Boast'), ('roast', 'Roast')], default='Boast', max_length=5),
        ),
    ]
